In [34]:
import numpy as np

In [35]:
a = np.array(["106", 43, 5723])
a

array(['106', '43', '5723'], dtype='<U21')

In [36]:
a.ndim

1

In [37]:
a.shape

(3,)

In [38]:
a.size

3

In [39]:
a.itemsize
# for simple no.s like  the output will be different
#(9, 10, 23)
#(9.0, 56, 45)
#("9", 4, 34)

84

In [40]:
np.ones(3)

array([1., 1., 1.])

In [41]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [42]:
np.ones((2,1,5))

array([[[1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.]]])

In [43]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [44]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
a = np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

To get an specific no.s in this

In [47]:
# this in the form of row and column 1: is where
a[3, 1:] 

array([13, 14, 15])

In [48]:
a[(2,1)]

9