In [33]:
import numpy as np

In [34]:
a = np.arange(36).reshape(6,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [35]:
a[2, 2:5]

array([14, 15, 16])

In [36]:
a[:3, 3]

array([ 3,  9, 15])

In [37]:
import pandas as pd

In [38]:
a = pd.Series(1)
a

0    1
dtype: int64

In [39]:
a = pd.Series([2,5,6])
a

0    2
1    5
2    6
dtype: int64

In [40]:
a = pd.Series([1,2,3,4], index=["a","b","c","d"])
a

a    1
b    2
c    3
d    4
dtype: int64

In [41]:
a = pd.Series([101,102,103,104], index=[1,2,3,4])
a

1    101
2    102
3    103
4    104
dtype: int64

In [42]:
a.ndim

1

In [43]:
a=pd.Series([1])
a

0    1
dtype: int64

In [44]:
a=[1, 2, 3]
a1=pd.DataFrame(a)
a1

0
0  1
1  2
2  3

In [45]:
b={12, 1, 14}
b1=pd.DataFrame(b)
b1

0
0   1
1  12
2  14

In [46]:
# To convert Series to Data Frame
a = pd.Series([2,5,6])
c1=pd.DataFrame(a)
c1

0
0  2
1  5
2  6

In [47]:
# Convert Array to Data Frame
a = np.array([106, 43, 5723])
D1=pd.DataFrame(a)
D1

0
0   106
1    43
2  5723

In [48]:
# To create a dataframe (Student, Class, )
a={ "Name":[1,2,3], "Class":[2,3,4] }
a

{'Name': [1, 2, 3], 'Class': [2, 3, 4]}

In [49]:
r=pd.DataFrame(a)
r

Name  Class
0     1      2
1     2      3
2     3      4

In [50]:
r["Name"][:1]

0    1
Name: Name, dtype: int64

In [51]:
r["Event"]=[23, 34, 56]

In [52]:
r

Name  Class  Event
0     1      2     23
1     2      3     34
2     3      4     56

In [53]:
r["Class"][1]="H"

In [54]:
r

Name Class  Event
0     1     2     23
1     2     H     34
2     3     4     56

In [55]:
del r["Name"]

In [56]:
r

Class  Event
0     2     23
1     H     34
2     4     56

loc for accesing the data row wise

In [57]:
r.loc[1]

Class     H
Event    34
Name: 1, dtype: object

In [58]:
r.loc[1][1]

34

In [59]:
r.loc[2][:]

Class     4
Event    56
Name: 2, dtype: object